TASK1:
  name: VQA
  type: VL-classifier
  num_labels: 3129
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/vqa/annotations
  features_h5path1: datasets/mscoco/resnet101_faster_rcnn_genome_imgfeats/volta/test_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 128
  eval_batch_size: 1024
  train_split: ''
  val_split: test
TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  dataroot: datasets/flickr30k
  features_h5path1: datasets/flickr30k/resnet101_faster_rcnn_genome_imgfeats/volta/flickr30k_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: datasets/flickr30k/annotations/test_ann.jsonl
  max_seq_length: 38
  max_region_num: 36
  batch_size: 64
  train_split: ''
  val_split: test
TASK10:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 10
  dataroot: data/refcoco+_unc/annotations
  features_h5path1: data/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
TASK11:
  name: refcoco+
  type: V-logit-fuse-self-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 11
  dataroot: data/refcoco+_unc/annotations
  features_h5path1: data/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
  layer_fusion_dropout: 0.1
TASK12:
  name: NLVR2
  type: VL-binary-classifier
  num_labels: 2
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  dataroot: datasets/nlvr2/annotations
  features_h5path1: datasets/nlvr2/resnet101_faster_rcnn_genome_imgfeats/volta/nlvr2_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 512
  train_split: ''
  val_split: test
TASK19:
  name: talk2car
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 19
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
TASK21:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 21
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  clf_latent_size: 128
  temperature: 0.5
TASK26:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 26
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  clf_latent_size: 128
  temperature: 0.5
TASK35:
  name: talk2car
  type: VL-keywordmlp
  loss: BCEWithLogitLoss
  process: normal
  task_id: 35
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  num_clf_layers: 1
TASK39:
  name: talk2car
  type: VL-contrast-separated
  loss: BCEInfoNCELoss
  process: normal
  task_id: 39
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  clf_latent_size: 128
  temperature: 0.5
  num_clf_layers: 1
  num_contrast_proj_layers: 1
  region_loss_weight: 0.8
  contrast_loss_weight: 0.2
TASK41:
  name: talk2car
  type: VL-contrast-separated
  loss: BCEInfoNCELoss
  process: normal
  task_id: 41
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  clf_latent_size: 128
  temperature: 0.5
  num_clf_layers: 1
  num_contrast_proj_layers: 1
  region_loss_weight: 0.6
  contrast_loss_weight: 0.4
TASK42:
  name: talk2car
  type: VL-contrast-separated
  loss: BCEInfoNCELoss
  process: normal
  task_id: 42
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  clf_latent_size: 128
  temperature: 0.5
  num_clf_layers: 1
  num_contrast_proj_layers: 1
  region_loss_weight: 0.5
  contrast_loss_weight: 0.5
TASK43:
  name: talk2car
  type: V-logit
  loss: ListNetLoss
  process: normal
  task_id: 43
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  temperature: 1
TASK44:
  name: talk2car
  type: VL-contrast-separated
  loss: ListNetInfoNCELoss
  process: normal
  task_id: 44
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  clf_latent_size: 128
  temperature: 0.5
  num_clf_layers: 1
  num_contrast_proj_layers: 1
  region_loss_weight: 0.5
  contrast_loss_weight: 0.5
  listnet_temperature: 1
TASK47:
  name: talk2car
  type: V-logit-fuse
  loss: BCEWithLogitLoss
  process: normal
  task_id: 47
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [1,3,5,7,9,11,13,15,17,19,21,23]
TASK48:
  name: talk2car
  type: V-logit-fuse
  loss: BCEWithLogitLoss
  process: normal
  task_id: 48
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [21,23]
TASK49:
  name: talk2car
  type: V-logit-fuse
  loss: BCEWithLogitLoss
  process: normal
  task_id: 49
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [19,21,23]
TASK59:
  name: talk2car
  type: V-logit-fuse-coarse-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 59
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
  layer_fusion_dropout: 0.1
TASK61:
  name: talk2car
  type: V-logit-fuse-fine-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 61
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
  layer_fusion_dropout: 0.2
TASK66:
  name: talk2car
  type: V-logit-fuse
  loss: BCEWithLogitLoss
  process: normal
  task_id: 66
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [14, 16, 18, 20, 22, 24]
TASK67:
  name: talk2car
  type: V-logit-fuse
  loss: BCEWithLogitLoss
  process: normal
  task_id: 67
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 24]
TASK68:
  name: talk2car
  type: V-logit-fuse-self-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 68
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
  layer_fusion_dropout: 0.1
TASK70:
  name: talk2car
  type: V-logit-fuse-self-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 70
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
  layer_fusion_dropout: 0.0
TASK71:
  name: talk2car
  type: V-logit-fuse-self-attention-text-vision
  loss: BCEWithLogitLoss
  process: normal
  task_id: 71
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
  layer_fusion_dropout: 0.1
TASK81:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 81
  dataroot: data/refcoco+_unc/annotations
  features_h5path1: data/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
TASK82:
  name: talk2car
  type: V-logit-fuse-self-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 82
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]
  layer_fusion_dropout: 0.1
TASK83:
  name: talk2car
  type: V-logit-fuse-self-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 83
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 21, 24, 27, 30, 33]
  layer_fusion_dropout: 0.1
TASK84:
  name: talk2car
  type: V-logit-fuse-self-attention-vseq-mean-pooled
  loss: BCEWithLogitLoss
  process: normal
  task_id: 84
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
  layer_fusion_dropout: 0.1
TASK85:
  name: talk2car
  type: V-logit-fuse-self-attention-vseq-mean-pooled
  loss: BCEWithLogitLoss
  process: normal
  task_id: 85
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 21, 24, 27, 30, 33]
  layer_fusion_dropout: 0.1
TASK86:
  name: refcoco+
  type: V-logit-fuse-self-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 86
  dataroot: data/refcoco+_unc/annotations
  features_h5path1: data/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 21, 24, 27, 30, 33]
  layer_fusion_dropout: 0.1
TASK87:
  name: refcoco+
  type: V-logit-fuse-self-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 87
  dataroot: data/refcoco+_unc/annotations
  features_h5path1: data/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 21, 24, 27, 30, 33]
  layer_fusion_dropout: 0.1
TASK90:
  name: refcoco+
  type: V-logit-fuse-self-attention
  loss: BCEWithLogitLoss
  process: normal
  task_id: 90
  dataroot: data/refcoco+_unc/annotations
  features_h5path1: data/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  num_clf_layers: 1
  fuse_layers: [0, 2, 4, 6, 8, 10, 21, 24, 27, 30, 33]
  layer_fusion_dropout: 0.2
TASK91:
  name: talk2carTgtObjCategorize
  type: VL-obj-categorize-probing
  loss: CrossEntropyLoss
  process: normal
  task_id: 91
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 256
  train_split: ''
  val_split: test
  embed_proj_size: 256
  attn_latent_size: 150
  num_obj_classes: 23
  num_clf_layers: 2
  clf_dropout: 0.2