TASK1:
  name: VQA
  type: VL-classifier
  num_labels: 3129
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/vqa/annotations
  features_h5path1: datasets/mscoco/resnet101_faster_rcnn_genome_imgfeats/volta/test_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 128
  eval_batch_size: 1024
  train_split: ''
  val_split: test
TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  dataroot: datasets/flickr30k
  features_h5path1: datasets/flickr30k/resnet101_faster_rcnn_genome_imgfeats/volta/flickr30k_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: datasets/flickr30k/annotations/test_ann.jsonl
  max_seq_length: 38
  max_region_num: 36
  batch_size: 64
  train_split: ''
  val_split: test
TASK10:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 10
  dataroot: data/refcoco+_unc/annotations
  features_h5path1: data/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 1024
  train_split: ''
  val_split: test
TASK12:
  name: NLVR2
  type: VL-binary-classifier
  num_labels: 2
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  dataroot: datasets/nlvr2/annotations
  features_h5path1: datasets/nlvr2/resnet101_faster_rcnn_genome_imgfeats/volta/nlvr2_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 38
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 512
  train_split: ''
  val_split: test
TASK19:
  name: talk2car
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 19
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
TASK21:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 21
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 32
  eval_batch_size: 512
  train_split: ''
  val_split: test
  clf_latent_size: 128
