TASK1:
  name: VQA
  type: VL-classifier
  num_labels: 3129
  loss: BCEWithLogitLoss
  process: normal
  task_id: 1
  dataroot: datasets/vqa/annotations
  features_h5path1: datasets/mscoco/resnet101_faster_rcnn_genome_imgfeats/volta/trainval_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 23
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
TASK8:
  name: RetrievalFlickr30k
  type: VL-logit
  num_labels: 1
  loss: CrossEntropyLoss
  process: retrieval
  task_id: 8
  dataroot: datasets/flickr30k
  features_h5path1: datasets/flickr30k/resnet101_faster_rcnn_genome_imgfeats/volta/flickr30k_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: datasets/flickr30k/annotations/train_ann.jsonl
  val_annotations_jsonpath: datasets/flickr30k/annotations/valid_ann.jsonl
  max_seq_length: 30
  max_region_num: 36
  batch_size: 64
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK10:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 10
  dataroot: data/refcoco+_unc/annotations
  features_h5path1: data/refcoco+_unc/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
TASK12:
  name: NLVR2
  type: VL-binary-classifier
  num_labels: 2
  loss: BCEWithLogitLoss
  process: nlvr
  task_id: 12
  dataroot: datasets/nlvr2/annotations
  features_h5path1: datasets/nlvr2/resnet101_faster_rcnn_genome_imgfeats/volta/nlvr2_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 40
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 512
  train_split: train
  val_split: dev
  lr: 0.00001
  num_epoch: 20
TASK19:
  name: talk2car
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 19
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
TASK20:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 20
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 1.0
TASK21:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 21
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 35
  clf_latent_size: 128
  temperature: 0.5
TASK22:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 22
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 0.2
TASK23:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 23
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 0.8
TASK24:
  name: talk2car
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 24
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 128
  eval_batch_size: 512
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
TASK25:
  name: talk2car
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 25
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
TASK26:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 26
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 128
  eval_batch_size: 512
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 0.5
TASK27:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 27
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 0.5
TASK28:
  name: talk2car
  type: VL-contrast
  loss: InfoNCELoss
  process: normal
  task_id: 28
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 256
  temperature: 0.5
TASK29:
  name: talk2carSeqLabel
  type: VL-multi-task-contrast
  loss: InfoNCESequenceLabelLoss
  process: normal
  task_id: 29
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 0.5
  region_loss_weight: 0.9
  sequence_loss_weight: 0.1
  num_token_clf_layers: 1
TASK30:
  name: talk2carSeqLabel
  type: VL-multi-task-contrast
  loss: InfoNCESequenceLabelLoss
  process: normal
  task_id: 30
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 0.5
  region_loss_weight: 0.95
  sequence_loss_weight: 0.05
  num_token_clf_layers: 1
TASK31:
  name: talk2carSeqLabel
  type: VL-multi-task-contrast
  loss: InfoNCESequenceLabelLoss
  process: normal
  task_id: 31
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 0.5
  region_loss_weight: 0.8
  sequence_loss_weight: 0.2
  num_token_clf_layers: 1
TASK32:
  name: talk2carSeqLabel
  type: VL-multi-task
  loss: BCESequenceLabelLoss
  process: normal
  task_id: 32
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 0.5
  region_loss_weight: 0.8
  sequence_loss_weight: 0.2
  num_token_clf_layers: 1
TASK33:
  name: talk2car
  type: V-logit
  loss: BCEWithLogitLoss
  process: normal
  task_id: 33
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  num_clf_layers: 2
TASK34:
  name: talk2car
  type: VL-contrast
  loss: BCEWithLogitLoss
  process: normal
  task_id: 34
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  clf_latent_size: 128
  temperature: 0.5
TASK35:
  name: talk2car
  type: VL-keywordmlp
  loss: BCEWithLogitLoss
  process: normal
  task_id: 35
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  num_clf_layers: 1
TASK36:
  name: talk2car
  type: VL-keywordmlp
  loss: BCEWithLogitLoss
  process: normal
  task_id: 35
  dataroot: data/talk2car/annotations
  features_h5path1: data/talk2car/resnet101_faster_rcnn_genome_imgfeats_centernet/volta/refcoco+_unc_dets36_feat.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 80
  max_region_num: 36
  batch_size: 64
  eval_batch_size: 256
  train_split: train
  val_split: val
  lr: 0.0001
  num_epoch: 20
  num_clf_layers: 2